rules:
  - id: csharp-input-validation
    languages: [csharp]
    severity: INFO
    message: Input validation
    pattern-either:
      - pattern: throw new ArgumentNullException(...)
      - pattern: throw new ArgumentException(...)
      - pattern: string.IsNullOrWhiteSpace(...)
